name: MouseTranslate
version: @version@
main: io.github.lee0701.mousetranslate.MouseTranslate
author: Lee0701
authors: [Lee0701, RanolP]
description: Discord & Spigot translate plugin that uses RatTranslate.
commands:
  mousetranslate:
    aliases: [mousetr, mtr]
    description: "MouseTranslation main command."
